// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using wonder_pick_pokemon_tcgp.src.data;

#nullable disable

namespace wonder_pick_pokemon_tcgp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250215152011_AddWonderPickTable")]
    partial class AddWonderPickTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("wonder_pick_pokemon_tcgp.src.entities.WonderPick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_criacao");

                    b.Property<int>("PosicaoFinal")
                        .HasColumnType("integer")
                        .HasColumnName("posicao_final");

                    b.Property<int>("PosicaoInicial")
                        .HasColumnType("integer")
                        .HasColumnName("posicao_inicial");

                    b.HasKey("Id");

                    b.ToTable("wonder_picks");
                });
#pragma warning restore 612, 618
        }
    }
}
